In [1]:
import numpy as np

In [2]:
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])

In [3]:
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [4]:
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [5]:
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])