In [1]:
import  numpy as np

In [2]:
n1 = np.array([1,2,3,4,5,6])
n1

array([1, 2, 3, 4, 5, 6])

In [3]:
type(n1)

numpy.ndarray

In [4]:
n2 = np.array([[1,2,3,4,5,6],[10,20,30,40,50,60]])

In [5]:
n2

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60]])

In [6]:
type(n2)

numpy.ndarray

In [7]:
n3 = np.zeros((2,3))

In [8]:
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
n4 = np.zeros((10,10))
n4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
n5 = np.full((5,5),(25))
n5

array([[25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25]])

In [11]:
n6= np.arange(10,51)
n6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [12]:
n7= np.arange(1,151,15)

In [14]:
n7

array([  1,  16,  31,  46,  61,  76,  91, 106, 121, 136])

In [16]:
n8 = np.random.randint(100,1000,10)
n8

array([100, 444, 665, 286, 414, 472, 361, 228, 300, 257])