In [1]:
import numpy as np

In [2]:
n1 = np.array([10,20])
n2 = np.array([40,50])

In [4]:
np.sum([n1,n2])

120

In [5]:
np.sum([n1,n2],axis = 0)

array([50, 70])

In [6]:
np.sum([n1,n2],axis = 1)1 = n1

array([30, 90])

In [7]:
n1 = n1 +1

In [8]:
n1

array([11, 21])

In [9]:
n2 = n2 -1
n2

array([39, 49])

In [10]:
n1 = n1 *2

In [11]:
n1

array([22, 42])

In [12]:
n1 = n1 /2
n1

array([11., 21.])

In [13]:
n1 = np.array([10,20,30,40,50])

In [14]:
np.mean(n1)

30.0

In [15]:
np.median(n1)

30.0

In [16]:
np.std(n1)

14.142135623730951